export { default as StudentCalendar } from './CalendarPage/Calendar'
export { default as Announcements } from './AnnouncementsPage/Announcements'
export { default as Courses } from './CoursesPage/Courses'
export { default as User } from './UserPage/User'
export { default as Instructors } from './InstructorPage/Instructors'